import Image from 'next/image'
import '../styles/globals.css'


export const metadata = {
  title: 'Disease Predictor',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header>
        <nav id="main-navbar">
            <div className="logo">
                <a href="index.html"><Image src="/phone-doctor.png" width={100} height={100} alt='logo' className="logo"/></a>
            </div>
            <div>
                <ul className="nav-links">
                    <li><a href="../index.html"><i className="fa-solid fa-house"></i> Home</a></li>
                    <li><a href="predictor.html">Predictor</a></li>
                    <li><a href="../consultation.html">Consultation</a></li>
                    <li><a href="../news">Newsletter</a></li>
                    <li><a href="../patient.html"><i className="fa-solid fa-user"></i> Account</a></li>
                </ul>
                <div className="burger">
                    <div className="line"></div>
                    <div className="line"></div>
                    <div className="line"></div>
                </div>
            </div>

        </nav>
    </header>
        {children}
        
    <footer>
        <div className="footer-content">
            <div className="footer-section">
                <a href="index.html"><Image src="/phone-doctor.png" width={100} height={100} alt='logo' className="logo"/></a>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua.
                </p>
                <div className="contact">
                    <span><i className="fas fa-phone"></i> &nbsp; 123-456-7890</span>
                    <span><i className="fas fa-envelope"></i> &nbsp; info@example.com</span>
                </div>
                <div className="socials">
                    <a href="#"><i className="fab fa-facebook"></i></a>
                    <a href="#"><i className="fab fa-twitter"></i></a>
                    <a href="#"><i className="fab fa-instagram"></i></a>
                    <a href="#"><i className="fab fa-linkedin"></i></a>
                </div>
            </div>
            <div className="footer-section links">
                <h2>Quick Links</h2>
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="template/predictor.html">Predictor</a></li>
                    <li><a href="consult.html">Consultation</a></li>
                    <li><a href="news.html">Newsletter</a></li>
                    <li><a href="patient.html">Account</a></li>
                </ul>
            </div>
            <div className="footer-section contact-form">
                <h2>Contact Us</h2>
                <form action="#" method="post">
                    <input type="email" name="email" className="text-input contact-input" placeholder="Your email address"/>
                    <textarea name="message" className="text-input contact-input" placeholder="Your message"></textarea>
                    <button type="submit" className="btn btn-big contact-btn">
                        <i className="fas fa-envelope"></i>
                        Send
                    </button>
                </form>
            </div>
        </div>
        <div className="footer-bottom">
            Copyright &copy; 2023 | Designed by Fonsah Pageo
        </div>
    </footer>
        </body>
    </html>
  )
}
